//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "", propOrder = {
//    "address1OrAddress2OrAddress3OrAddress4OrAddress5OrMailcodeOrPoboxOrRoomOrAddressFloorOrBuildingOrStreetOrCityOrCountyOrStateOrPostcodeOrCountryOrText"
//})


@XmlType(name = "", propOrder = {
    "address1",
    "address2",
    "address3",
    "address4",
    "address5",
    "mailcode",
    "pobox",
     "room",
      "addressFloor",
       "building",
        "street",
         "city",
          "county",
           "state",
            "postcode",
"country",
"text"
})




@XmlRootElement(name = "address")
public class Address {
    
    @XmlElement(name = "address-1", required = true)
    protected Address1 address1;
    @XmlElement(name = "address-2", required = true)
    protected Address2 address2;  
        
        
        @XmlElement(name = "address-3", required = true )
         Address3    address3;  
        @XmlElement(name = "address-4", required = true )
         Address4     address4;  
        @XmlElement(name = "address-5", required = true )
        Address5        address5;
        @XmlElement(name = "mailcode", required = true)
         Mailcode   mailcode;    
        @XmlElement(name = "pobox", required = true)
        Pobox   pobox;     
        @XmlElement(name = "room", required = true)
         Room      room; 
        @XmlElement(name = "address-floor", required = true)
         AddressFloor   addressFloor;    
        @XmlElement(name = "building", required = true)
         Building     building;  
        @XmlElement(name = "street", required = true)
        Street       street; 
        @XmlElement(name = "city", required = true)
        City       city; 
        @XmlElement(name = "county", required = true)
        County       county;
        @XmlElement(name = "state", required = true)
        State      state;  
        @XmlElement(name = "postcode", required = true)
        Postcode       postcode; 
        @XmlElement(name = "country", required = true)
        Country       country; 
        @XmlElement(name = "text", required = true)
       Text text;

    public Address1 getAddress1() {
        return address1;
    }

    public void setAddress1(Address1 address1) {
        this.address1 = address1;
    }

    public Address2 getAddress2() {
        return address2;
    }

    public void setAddress2(Address2 address2) {
        this.address2 = address2;
    }

    public Address3 getAddress3() {
        return address3;
    }

    public void setAddress3(Address3 address3) {
        this.address3 = address3;
    }

    public Address4 getAddress4() {
        return address4;
    }

    public void setAddress4(Address4 address4) {
        this.address4 = address4;
    }

    public Address5 getAddress5() {
        return address5;
    }

    public void setAddress5(Address5 address5) {
        this.address5 = address5;
    }

    public Mailcode getMailcode() {
        return mailcode;
    }

    public void setMailcode(Mailcode mailcode) {
        this.mailcode = mailcode;
    }

    public Pobox getPobox() {
        return pobox;
    }

    public void setPobox(Pobox pobox) {
        this.pobox = pobox;
    }

    public Room getRoom() {
        return room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public AddressFloor getAddressFloor() {
        return addressFloor;
    }

    public void setAddressFloor(AddressFloor addressFloor) {
        this.addressFloor = addressFloor;
    }

    public Building getBuilding() {
        return building;
    }

    public void setBuilding(Building building) {
        this.building = building;
    }

    public Street getStreet() {
        return street;
    }

    public void setStreet(Street street) {
        this.street = street;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public County getCounty() {
        return county;
    }

    public void setCounty(County county) {
        this.county = county;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public Postcode getPostcode() {
        return postcode;
    }

    public void setPostcode(Postcode postcode) {
        this.postcode = postcode;
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public Text getText() {
        return text;
    }

    public void setText(Text text) {
        this.text = text;
    }
    
        
        
        

}
