//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno"
})
@XmlRootElement(name = "book")
public class Book {

    @XmlElements({
        @XmlElement(name = "text", required = true, type = Text.class),
        @XmlElement(name = "author", required = true, type = Author.class),
        @XmlElement(name = "book-title", required = true, type = BookTitle.class),
        @XmlElement(name = "conference", required = true, type = Conference.class),
        @XmlElement(name = "subtitle", required = true, type = Subtitle.class),
        @XmlElement(name = "subname", required = true, type = Subname.class),
        @XmlElement(name = "edition", required = true, type = Edition.class),
        @XmlElement(name = "imprint", required = true, type = Imprint.class),
        @XmlElement(name = "vid", required = true, type = Vid.class),
        @XmlElement(name = "ino", required = true, type = Ino.class),
        @XmlElement(name = "descrip", required = true, type = Descrip.class),
        @XmlElement(name = "series", required = true, type = Series.class),
        @XmlElement(name = "notes", required = true, type = Notes.class),
        @XmlElement(name = "absno", required = true, type = Absno.class),
        @XmlElement(name = "location", required = true, type = Location.class),
        @XmlElement(name = "pubid", required = true, type = Pubid.class),
        @XmlElement(name = "bookno", required = true, type = Bookno.class),
        @XmlElement(name = "class", required = true, type = Class.class),
        @XmlElement(name = "keyword", required = true, type = Keyword.class),
        @XmlElement(name = "cpyrt", required = true, type = Cpyrt.class),
        @XmlElement(name = "doi", required = true, type = Doi.class),
        @XmlElement(name = "issn", required = true, type = Issn.class),
        @XmlElement(name = "isbn", required = true, type = Isbn.class),
        @XmlElement(name = "refno", required = true, type = Refno.class)
    })
    protected List<Object> textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno;

    /**
     * Gets the value of the textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Text }
     * {@link Author }
     * {@link BookTitle }
     * {@link Conference }
     * {@link Subtitle }
     * {@link Subname }
     * {@link Edition }
     * {@link Imprint }
     * {@link Vid }
     * {@link Ino }
     * {@link Descrip }
     * {@link Series }
     * {@link Notes }
     * {@link Absno }
     * {@link Location }
     * {@link Pubid }
     * {@link Bookno }
     * {@link Class }
     * {@link Keyword }
     * {@link Cpyrt }
     * {@link Doi }
     * {@link Issn }
     * {@link Isbn }
     * {@link Refno }
     * 
     * 
     */
    public List<Object> getTextOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno() {
        if (textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno == null) {
            textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno = new ArrayList<Object>();
        }
        return this.textOrAuthorOrBookTitleOrConferenceOrSubtitleOrSubnameOrEditionOrImprintOrVidOrInoOrDescripOrSeriesOrNotesOrAbsnoOrLocationOrPubidOrBooknoOrClazzOrKeywordOrCpyrtOrDoiOrIssnOrIsbnOrRefno;
    }

}
