//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patcitOrNplcit",
    "relPassageOrCategoryOrRelClaims",
    "correspondingDocs"
})
@XmlRootElement(name = "citation")
public class Citation {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "cited-phase")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String citedPhase;
    @XmlAttribute(name = "cited-by")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String citedBy;
    @XmlElements({
        @XmlElement(name = "patcit", required = true, type = Patcit.class),
        @XmlElement(name = "nplcit", required = true, type = Nplcit.class)
    })
    protected List<Object> patcitOrNplcit;
    @XmlElements({
        @XmlElement(name = "rel-passage", type = RelPassage.class),
        @XmlElement(name = "category", type = Category.class),
        @XmlElement(name = "rel-claims", type = RelClaims.class)
    })
    protected List<Object> relPassageOrCategoryOrRelClaims;
    @XmlElement(name = "corresponding-docs")
    protected List<CorrespondingDocs> correspondingDocs;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    public String getCitedPhase() {
        return citedPhase;
    }

    public void setCitedPhase(String citedPhase) {
        this.citedPhase = citedPhase;
    }

    public String getCitedBy() {
        return citedBy;
    }

    public void setCitedBy(String citedBy) {
        this.citedBy = citedBy;
    }
    
    

    /**
     * Gets the value of the srepPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
   
    /**
     * Gets the value of the patcitOrNplcit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patcitOrNplcit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatcitOrNplcit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Patcit }
     * {@link Nplcit }
     * 
     * 
     */
    public List<Object> getPatcitOrNplcit() {
        if (patcitOrNplcit == null) {
            patcitOrNplcit = new ArrayList<Object>();
        }
        return this.patcitOrNplcit;
    }

    /**
     * Gets the value of the relPassageOrCategoryOrRelClaims property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relPassageOrCategoryOrRelClaims property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelPassageOrCategoryOrRelClaims().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelPassage }
     * {@link Category }
     * {@link RelClaims }
     * 
     * 
     */
    public List<Object> getRelPassageOrCategoryOrRelClaims() {
        if (relPassageOrCategoryOrRelClaims == null) {
            relPassageOrCategoryOrRelClaims = new ArrayList<Object>();
        }
        return this.relPassageOrCategoryOrRelClaims;
    }

    /**
     * Gets the value of the correspondingDocs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the correspondingDocs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorrespondingDocs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CorrespondingDocs }
     * 
     * 
     */
    public List<CorrespondingDocs> getCorrespondingDocs() {
        if (correspondingDocs == null) {
            correspondingDocs = new ArrayList<CorrespondingDocs>();
        }
        return this.correspondingDocs;
    }

}
