//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText"
})
@XmlRootElement(name = "classification-ipcr")
public class ClassificationIpcr {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "sequence")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sequence;
    @XmlElements({
        @XmlElement(name = "ipc-version-indicator", required = true, type = IpcVersionIndicator.class),
        @XmlElement(name = "classification-level", required = true, type = ClassificationLevel.class),
        @XmlElement(name = "section", required = true, type = Section.class),
        @XmlElement(name = "class", required = true, type = Clazz.class),
        @XmlElement(name = "subclass", required = true, type = Subclass.class),
        @XmlElement(name = "main-group", required = true, type = MainGroup.class),
        @XmlElement(name = "subgroup", required = true, type = Subgroup.class),
        @XmlElement(name = "symbol-position", required = true, type = SymbolPosition.class),
        @XmlElement(name = "classification-value", required = true, type = ClassificationValue.class),
        @XmlElement(name = "action-date", required = true, type = ActionDate.class),
        @XmlElement(name = "generating-office", required = true, type = GeneratingOffice.class),
        @XmlElement(name = "classification-status", required = true, type = ClassificationStatus.class),
        @XmlElement(name = "classification-data-source", required = true, type = ClassificationDataSource.class),
        @XmlElement(name = "text", required = true, type = Text.class)
    })
    protected List<Object> ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IpcVersionIndicator }
     * {@link ClassificationLevel }
     * {@link Section }
     * {@link Class }
     * {@link Subclass }
     * {@link MainGroup }
     * {@link Subgroup }
     * {@link SymbolPosition }
     * {@link ClassificationValue }
     * {@link ActionDate }
     * {@link GeneratingOffice }
     * {@link ClassificationStatus }
     * {@link ClassificationDataSource }
     * {@link Text }
     * 
     * 
     */
    public List<Object> getIpcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText() {
        if (ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText == null) {
            ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText = new ArrayList<Object>();
        }
        return this.ipcVersionIndicatorOrClassificationLevelOrSectionOrClazzOrSubclassOrMainGroupOrSubgroupOrSymbolPositionOrClassificationValueOrActionDateOrGeneratingOfficeOrClassificationStatusOrClassificationDataSourceOrText;
    }

}
