//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SequenceListDoc }
     * 
     */
    public SequenceListDoc createSequenceListDoc() {
        return new SequenceListDoc();
    }

    /**
     * Create an instance of {@link Srchterm }
     * 
     */
    public Srchterm createSrchterm() {
        return new Srchterm();
    }

    /**
     * Create an instance of {@link Received }
     * 
     */
    public Received createReceived() {
        return new Received();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link SequenceList }
     * 
     */
    public SequenceList createSequenceList() {
        return new SequenceList();
    }

    /**
     * Create an instance of {@link Sersect }
     * 
     */
    public Sersect createSersect() {
        return new Sersect();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link RelPassage }
     * 
     */
    public RelPassage createRelPassage() {
        return new RelPassage();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Passage }
     * 
     */
    public Passage createPassage() {
        return new Passage();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link RelClaims }
     * 
     */
    public RelClaims createRelClaims() {
        return new RelClaims();
    }

    /**
     * Create an instance of {@link Edate }
     * 
     */
    public Edate createEdate() {
        return new Edate();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Patcit }
     * 
     */
    public Patcit createPatcit() {
        return new Patcit();
    }

    /**
     * Create an instance of {@link DocumentId }
     * 
     */
    public DocumentId createDocumentId() {
        return new DocumentId();
    }

    /**
     * Create an instance of {@link InventionTitle }
     * 
     */
    public InventionTitle createInventionTitle() {
        return new InventionTitle();
    }

    /**
     * Create an instance of {@link ClassificationValue }
     * 
     */
    public ClassificationValue createClassificationValue() {
        return new ClassificationValue();
    }

    /**
     * Create an instance of {@link Confsponsor }
     * 
     */
    public Confsponsor createConfsponsor() {
        return new Confsponsor();
    }

    /**
     * Create an instance of {@link ClassificationLocarno }
     * 
     */
    public ClassificationLocarno createClassificationLocarno() {
        return new ClassificationLocarno();
    }

    /**
     * Create an instance of {@link Edition }
     * 
     */
    public Edition createEdition() {
        return new Edition();
    }

    /**
     * Create an instance of {@link FurtherClassification }
     * 
     */
    public FurtherClassification createFurtherClassification() {
        return new FurtherClassification();
    }

    /**
     * Create an instance of {@link Ead }
     * 
     */
    public Ead createEad() {
        return new Ead();
    }

    /**
     * Create an instance of {@link Postcode }
     * 
     */
    public Postcode createPostcode() {
        return new Postcode();
    }

    /**
     * Create an instance of {@link UnlinkedIndexingCode }
     * 
     */
    public UnlinkedIndexingCode createUnlinkedIndexingCode() {
        return new UnlinkedIndexingCode();
    }

    /**
     * Create an instance of {@link LinkedIndexingCodeGroup }
     * 
     */
    public LinkedIndexingCodeGroup createLinkedIndexingCodeGroup() {
        return new LinkedIndexingCodeGroup();
    }

    /**
     * Create an instance of {@link SubLinkedIndexingCode }
     * 
     */
    public SubLinkedIndexingCode createSubLinkedIndexingCode() {
        return new SubLinkedIndexingCode();
    }

    /**
     * Create an instance of {@link Ppl }
     * 
     */
    public Ppl createPpl() {
        return new Ppl();
    }

    /**
     * Create an instance of {@link MiddleName }
     * 
     */
    public MiddleName createMiddleName() {
        return new MiddleName();
    }

    /**
     * Create an instance of {@link ClassificationDataSource }
     * 
     */
    public ClassificationDataSource createClassificationDataSource() {
        return new ClassificationDataSource();
    }

    /**
     * Create an instance of {@link Prefix }
     * 
     */
    public Prefix createPrefix() {
        return new Prefix();
    }

    /**
     * Create an instance of {@link Linef }
     * 
     */
    public Linef createLinef() {
        return new Linef();
    }

    /**
     * Create an instance of {@link Linel }
     * 
     */
    public Linel createLinel() {
        return new Linel();
    }

    /**
     * Create an instance of {@link Ppf }
     * 
     */
    public Ppf createPpf() {
        return new Ppf();
    }

    /**
     * Create an instance of {@link Paral }
     * 
     */
    public Paral createParal() {
        return new Paral();
    }

    /**
     * Create an instance of {@link ActionDate }
     * 
     */
    public ActionDate createActionDate() {
        return new ActionDate();
    }

    /**
     * Create an instance of {@link Artid }
     * 
     */
    public Artid createArtid() {
        return new Artid();
    }

    /**
     * Create an instance of {@link Srchdate }
     * 
     */
    public Srchdate createSrchdate() {
        return new Srchdate();
    }

    /**
     * Create an instance of {@link Paraf }
     * 
     */
    public Paraf createParaf() {
        return new Paraf();
    }

    /**
     * Create an instance of {@link Continuation }
     * 
     */
    public Continuation createContinuation() {
        return new Continuation();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link Figure }
     * 
     */
    public Figure createFigure() {
        return new Figure();
    }

    /**
     * Create an instance of {@link Img }
     * 
     */
    public Img createImg() {
        return new Img();
    }

    /**
     * Create an instance of {@link Division }
     * 
     */
    public Division createDivision() {
        return new Division();
    }

    /**
     * Create an instance of {@link Conftitle }
     * 
     */
    public Conftitle createConftitle() {
        return new Conftitle();
    }

    /**
     * Create an instance of {@link Isbn }
     * 
     */
    public Isbn createIsbn() {
        return new Isbn();
    }

    /**
     * Create an instance of {@link DocumentCorrected }
     * 
     */
    public DocumentCorrected createDocumentCorrected() {
        return new DocumentCorrected();
    }

    /**
     * Create an instance of {@link SimplePatentDocument }
     * 
     */
    public SimplePatentDocument createSimplePatentDocument() {
        return new SimplePatentDocument();
    }

    /**
     * Create an instance of {@link BibliographicData }
     * 
     */
    public BibliographicData createBibliographicData() {
        return new BibliographicData();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Claims }
     * 
     */
    public Claims createClaims() {
        return new Claims();
    }

    /**
     * Create an instance of {@link Drawings }
     * 
     */
    public Drawings createDrawings() {
        return new Drawings();
    }

    /**
     * Create an instance of {@link SearchReportData }
     * 
     */
    public SearchReportData createSearchReportData() {
        return new SearchReportData();
    }

    /**
     * Create an instance of {@link Applicants }
     * 
     */
    public Applicants createApplicants() {
        return new Applicants();
    }

    /**
     * Create an instance of {@link Applicant }
     * 
     */
    public Applicant createApplicant() {
        return new Applicant();
    }

    /**
     * Create an instance of {@link FirstLastName }
     * 
     */
    public FirstLastName createFirstLastName() {
        return new FirstLastName();
    }

    /**
     * Create an instance of {@link Dtext }
     * 
     */
    public Dtext createDtext() {
        return new Dtext();
    }

    /**
     * Create an instance of {@link CorrespondenceAddress }
     * 
     */
    public CorrespondenceAddress createCorrespondenceAddress() {
        return new CorrespondenceAddress();
    }

    /**
     * Create an instance of {@link CustomerNumber }
     * 
     */
    public CustomerNumber createCustomerNumber() {
        return new CustomerNumber();
    }

    /**
     * Create an instance of {@link Addressbook }
     * 
     */
    public Addressbook createAddressbook() {
        return new Addressbook();
    }

    /**
     * Create an instance of {@link PriorityClaims }
     * 
     */
    public PriorityClaims createPriorityClaims() {
        return new PriorityClaims();
    }

    /**
     * Create an instance of {@link PriorityClaim }
     * 
     */
    public PriorityClaim createPriorityClaim() {
        return new PriorityClaim();
    }

    /**
     * Create an instance of {@link Para }
     * 
     */
    public Para createPara() {
        return new Para();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link Accepted }
     * 
     */
    public Accepted createAccepted() {
        return new Accepted();
    }

    /**
     * Create an instance of {@link Revised }
     * 
     */
    public Revised createRevised() {
        return new Revised();
    }

    /**
     * Create an instance of {@link Misc }
     * 
     */
    public Misc createMisc() {
        return new Misc();
    }

    /**
     * Create an instance of {@link ParentDoc }
     * 
     */
    public ParentDoc createParentDoc() {
        return new ParentDoc();
    }

    /**
     * Create an instance of {@link ParentGrantDocument }
     * 
     */
    public ParentGrantDocument createParentGrantDocument() {
        return new ParentGrantDocument();
    }

    /**
     * Create an instance of {@link ParentPctDocument }
     * 
     */
    public ParentPctDocument createParentPctDocument() {
        return new ParentPctDocument();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Inventors }
     * 
     */
    public Inventors createInventors() {
        return new Inventors();
    }

    /**
     * Create an instance of {@link Inventor }
     * 
     */
    public Inventor createInventor() {
        return new Inventor();
    }

    /**
     * Create an instance of {@link DeceasedInventor }
     * 
     */
    public DeceasedInventor createDeceasedInventor() {
        return new DeceasedInventor();
    }

    /**
     * Create an instance of {@link Doi }
     * 
     */
    public Doi createDoi() {
        return new Doi();
    }

    /**
     * Create an instance of {@link PublicationReference }
     * 
     */
    public PublicationReference createPublicationReference() {
        return new PublicationReference();
    }

    /**
     * Create an instance of {@link Synonym }
     * 
     */
    public Synonym createSynonym() {
        return new Synonym();
    }

    /**
     * Create an instance of {@link Subname }
     * 
     */
    public Subname createSubname() {
        return new Subname();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link Orgname }
     * 
     */
    public Orgname createOrgname() {
        return new Orgname();
    }

    /**
     * Create an instance of {@link FirstName }
     * 
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link SecondLastName }
     * 
     */
    public SecondLastName createSecondLastName() {
        return new SecondLastName();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link Iid }
     * 
     */
    public Iid createIid() {
        return new Iid();
    }

    /**
     * Create an instance of {@link Department }
     * 
     */
    public Department createDepartment() {
        return new Department();
    }

    /**
     * Create an instance of {@link RegisteredNumber }
     * 
     */
    public RegisteredNumber createRegisteredNumber() {
        return new RegisteredNumber();
    }

    /**
     * Create an instance of {@link DocPage }
     * 
     */
    public DocPage createDocPage() {
        return new DocPage();
    }

    /**
     * Create an instance of {@link Imprint }
     * 
     */
    public Imprint createImprint() {
        return new Imprint();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Pubdate }
     * 
     */
    public Pubdate createPubdate() {
        return new Pubdate();
    }

    /**
     * Create an instance of {@link Conference }
     * 
     */
    public Conference createConference() {
        return new Conference();
    }

    /**
     * Create an instance of {@link Confdate }
     * 
     */
    public Confdate createConfdate() {
        return new Confdate();
    }

    /**
     * Create an instance of {@link Confno }
     * 
     */
    public Confno createConfno() {
        return new Confno();
    }

    /**
     * Create an instance of {@link Confplace }
     * 
     */
    public Confplace createConfplace() {
        return new Confplace();
    }

    /**
     * Create an instance of {@link Nplcit }
     * 
     */
    public Nplcit createNplcit() {
        return new Nplcit();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link Online }
     * 
     */
    public Online createOnline() {
        return new Online();
    }

    /**
     * Create an instance of {@link Othercit }
     * 
     */
    public Othercit createOthercit() {
        return new Othercit();
    }

    /**
     * Create an instance of {@link Claim }
     * 
     */
    public Claim createClaim() {
        return new Claim();
    }

    /**
     * Create an instance of {@link Mst }
     * 
     */
    public Mst createMst() {
        return new Mst();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link Msn }
     * 
     */
    public Msn createMsn() {
        return new Msn();
    }

    /**
     * Create an instance of {@link ClassificationLevel }
     * 
     */
    public ClassificationLevel createClassificationLevel() {
        return new ClassificationLevel();
    }

    /**
     * Create an instance of {@link ChildDoc }
     * 
     */
    public ChildDoc createChildDoc() {
        return new ChildDoc();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link Url }
     * 
     */
    public Url createUrl() {
        return new Url();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Pubid }
     * 
     */
    public Pubid createPubid() {
        return new Pubid();
    }

    /**
     * Create an instance of {@link Room }
     * 
     */
    public Room createRoom() {
        return new Room();
    }

    /**
     * Create an instance of {@link Hostno }
     * 
     */
    public Hostno createHostno() {
        return new Hostno();
    }

    /**
     * Create an instance of {@link Correction }
     * 
     */
    public Correction createCorrection() {
        return new Correction();
    }

    /**
     * Create an instance of {@link GazetteReference }
     * 
     */
    public GazetteReference createGazetteReference() {
        return new GazetteReference();
    }

    /**
     * Create an instance of {@link Grantee }
     * 
     */
    public Grantee createGrantee() {
        return new Grantee();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link Residence }
     * 
     */
    public Residence createResidence() {
        return new Residence();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Chapter }
     * 
     */
    public Chapter createChapter() {
        return new Chapter();
    }

    /**
     * Create an instance of {@link UtilityModelBasis }
     * 
     */
    public UtilityModelBasis createUtilityModelBasis() {
        return new UtilityModelBasis();
    }

    /**
     * Create an instance of {@link Address4 }
     * 
     */
    public Address4 createAddress4() {
        return new Address4();
    }

    /**
     * Create an instance of {@link Address3 }
     * 
     */
    public Address3 createAddress3() {
        return new Address3();
    }

    /**
     * Create an instance of {@link Address2 }
     * 
     */
    public Address2 createAddress2() {
        return new Address2();
    }

    /**
     * Create an instance of {@link Address1 }
     * 
     */
    public Address1 createAddress1() {
        return new Address1();
    }

    /**
     * Create an instance of {@link Address5 }
     * 
     */
    public Address5 createAddress5() {
        return new Address5();
    }

    /**
     * Create an instance of {@link Reissue }
     * 
     */
    public Reissue createReissue() {
        return new Reissue();
    }

    /**
     * Create an instance of {@link ClaimText }
     * 
     */
    public ClaimText createClaimText() {
        return new ClaimText();
    }

    /**
     * Create an instance of {@link ReferencesCited }
     * 
     */
    public ReferencesCited createReferencesCited() {
        return new ReferencesCited();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link Pp }
     * 
     */
    public Pp createPp() {
        return new Pp();
    }

    /**
     * Create an instance of {@link Serial }
     * 
     */
    public Serial createSerial() {
        return new Serial();
    }

    /**
     * Create an instance of {@link Descrip }
     * 
     */
    public Descrip createDescrip() {
        return new Descrip();
    }

    /**
     * Create an instance of {@link Vid }
     * 
     */
    public Vid createVid() {
        return new Vid();
    }

    /**
     * Create an instance of {@link Ino }
     * 
     */
    public Ino createIno() {
        return new Ino();
    }

    /**
     * Create an instance of {@link Issn }
     * 
     */
    public Issn createIssn() {
        return new Issn();
    }

    /**
     * Create an instance of {@link Cpyrt }
     * 
     */
    public Cpyrt createCpyrt() {
        return new Cpyrt();
    }

    /**
     * Create an instance of {@link Street }
     * 
     */
    public Street createStreet() {
        return new Street();
    }

    /**
     * Create an instance of {@link Substitution }
     * 
     */
    public Substitution createSubstitution() {
        return new Substitution();
    }

    /**
     * Create an instance of {@link ClassificationIpcr }
     * 
     */
    public ClassificationIpcr createClassificationIpcr() {
        return new ClassificationIpcr();
    }

    /**
     * Create an instance of {@link IpcVersionIndicator }
     * 
     */
    public IpcVersionIndicator createIpcVersionIndicator() {
        return new IpcVersionIndicator();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Class }
     * 
     */
    public Clazz createClazz() {
        return new Clazz();
    }

    /**
     * Create an instance of {@link Subclass }
     * 
     */
    public Subclass createSubclass() {
        return new Subclass();
    }

    /**
     * Create an instance of {@link MainGroup }
     * 
     */
    public MainGroup createMainGroup() {
        return new MainGroup();
    }

    /**
     * Create an instance of {@link Subgroup }
     * 
     */
    public Subgroup createSubgroup() {
        return new Subgroup();
    }

    /**
     * Create an instance of {@link SymbolPosition }
     * 
     */
    public SymbolPosition createSymbolPosition() {
        return new SymbolPosition();
    }

    /**
     * Create an instance of {@link GeneratingOffice }
     * 
     */
    public GeneratingOffice createGeneratingOffice() {
        return new GeneratingOffice();
    }

    /**
     * Create an instance of {@link ClassificationStatus }
     * 
     */
    public ClassificationStatus createClassificationStatus() {
        return new ClassificationStatus();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Refno }
     * 
     */
    public Refno createRefno() {
        return new Refno();
    }

    /**
     * Create an instance of {@link ClassificationsIpcr }
     * 
     */
    public ClassificationsIpcr createClassificationsIpcr() {
        return new ClassificationsIpcr();
    }

    /**
     * Create an instance of {@link Mailcode }
     * 
     */
    public Mailcode createMailcode() {
        return new Mailcode();
    }

    /**
     * Create an instance of {@link CorrespondingDocs }
     * 
     */
    public CorrespondingDocs createCorrespondingDocs() {
        return new CorrespondingDocs();
    }

    /**
     * Create an instance of {@link PreviouslyFiledApplication }
     * 
     */
    public PreviouslyFiledApplication createPreviouslyFiledApplication() {
        return new PreviouslyFiledApplication();
    }

    /**
     * Create an instance of {@link Hosttitle }
     * 
     */
    public Hosttitle createHosttitle() {
        return new Hosttitle();
    }

    /**
     * Create an instance of {@link Avail }
     * 
     */
    public Avail createAvail() {
        return new Avail();
    }

    /**
     * Create an instance of {@link Serpart }
     * 
     */
    public Serpart createSerpart() {
        return new Serpart();
    }

    /**
     * Create an instance of {@link County }
     * 
     */
    public County createCounty() {
        return new County();
    }

    /**
     * Create an instance of {@link AdditionalInfo }
     * 
     */
    public AdditionalInfo createAdditionalInfo() {
        return new AdditionalInfo();
    }

    /**
     * Create an instance of {@link ApplicationReference }
     * 
     */
    public ApplicationReference createApplicationReference() {
        return new ApplicationReference();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link RelatedDocuments }
     * 
     */
    public RelatedDocuments createRelatedDocuments() {
        return new RelatedDocuments();
    }

    /**
     * Create an instance of {@link Addition }
     * 
     */
    public Addition createAddition() {
        return new Addition();
    }

    /**
     * Create an instance of {@link ContinuationInPart }
     * 
     */
    public ContinuationInPart createContinuationInPart() {
        return new ContinuationInPart();
    }

    /**
     * Create an instance of {@link ContinuingReissue }
     * 
     */
    public ContinuingReissue createContinuingReissue() {
        return new ContinuingReissue();
    }

    /**
     * Create an instance of {@link Reexamination }
     * 
     */
    public Reexamination createReexamination() {
        return new Reexamination();
    }

    /**
     * Create an instance of {@link RelatedPublication }
     * 
     */
    public RelatedPublication createRelatedPublication() {
        return new RelatedPublication();
    }

    /**
     * Create an instance of {@link Line }
     * 
     */
    public Line createLine() {
        return new Line();
    }

    /**
     * Create an instance of {@link OnlineTitle }
     * 
     */
    public OnlineTitle createOnlineTitle() {
        return new OnlineTitle();
    }

    /**
     * Create an instance of {@link Atl }
     * 
     */
    public Atl createAtl() {
        return new Atl();
    }

    /**
     * Create an instance of {@link Absno }
     * 
     */
    public Absno createAbsno() {
        return new Absno();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Grantees }
     * 
     */
    public Grantees createGrantees() {
        return new Grantees();
    }

    /**
     * Create an instance of {@link Sdate }
     * 
     */
    public Sdate createSdate() {
        return new Sdate();
    }

    /**
     * Create an instance of {@link Colf }
     * 
     */
    public Colf createColf() {
        return new Colf();
    }

    /**
     * Create an instance of {@link Parties }
     * 
     */
    public Parties createParties() {
        return new Parties();
    }

    /**
     * Create an instance of {@link Agents }
     * 
     */
    public Agents createAgents() {
        return new Agents();
    }

    /**
     * Create an instance of {@link ClassificationIpc }
     * 
     */
    public ClassificationIpc createClassificationIpc() {
        return new ClassificationIpc();
    }

    /**
     * Create an instance of {@link Coll }
     * 
     */
    public Coll createColl() {
        return new Coll();
    }

    /**
     * Create an instance of {@link PctOrRegionalFilingData }
     * 
     */
    public PctOrRegionalFilingData createPctOrRegionalFilingData() {
        return new PctOrRegionalFilingData();
    }

    /**
     * Create an instance of {@link BookTitle }
     * 
     */
    public BookTitle createBookTitle() {
        return new BookTitle();
    }

    /**
     * Create an instance of {@link AddressFloor }
     * 
     */
    public AddressFloor createAddressFloor() {
        return new AddressFloor();
    }

    /**
     * Create an instance of {@link Pobox }
     * 
     */
    public Pobox createPobox() {
        return new Pobox();
    }

    /**
     * Create an instance of {@link ClassificationNational }
     * 
     */
    public ClassificationNational createClassificationNational() {
        return new ClassificationNational();
    }

    /**
     * Create an instance of {@link Bookno }
     * 
     */
    public Bookno createBookno() {
        return new Bookno();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Datecit }
     * 
     */
    public Datecit createDatecit() {
        return new Datecit();
    }

    /**
     * Create an instance of {@link PctOrRegionalPublishingData }
     * 
     */
    public PctOrRegionalPublishingData createPctOrRegionalPublishingData() {
        return new PctOrRegionalPublishingData();
    }

    /**
     * Create an instance of {@link Building }
     * 
     */
    public Building createBuilding() {
        return new Building();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     */
    public Subtitle createSubtitle() {
        return new Subtitle();
    }

}
