//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicants",
    "inventors",
    "correspondenceAddress",
    "agents",
    "grantees"
})
@XmlRootElement(name = "parties")
public class Parties {

    @XmlElement(required = true)
    protected Applicants applicants;
    protected Inventors inventors;
    @XmlElement(name = "correspondence-address")
    protected CorrespondenceAddress correspondenceAddress;
    protected Agents agents;
    protected Grantees grantees;

    /**
     * Gets the value of the applicants property.
     * 
     * @return
     *     possible object is
     *     {@link Applicants }
     *     
     */
    public Applicants getApplicants() {
        return applicants;
    }

    /**
     * Sets the value of the applicants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Applicants }
     *     
     */
    public void setApplicants(Applicants value) {
        this.applicants = value;
    }

    /**
     * Gets the value of the inventors property.
     * 
     * @return
     *     possible object is
     *     {@link Inventors }
     *     
     */
    public Inventors getInventors() {
        return inventors;
    }

    /**
     * Sets the value of the inventors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inventors }
     *     
     */
    public void setInventors(Inventors value) {
        this.inventors = value;
    }

    /**
     * Gets the value of the correspondenceAddress property.
     * 
     * @return
     *     possible object is
     *     {@link CorrespondenceAddress }
     *     
     */
    public CorrespondenceAddress getCorrespondenceAddress() {
        return correspondenceAddress;
    }

    /**
     * Sets the value of the correspondenceAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorrespondenceAddress }
     *     
     */
    public void setCorrespondenceAddress(CorrespondenceAddress value) {
        this.correspondenceAddress = value;
    }

    /**
     * Gets the value of the agents property.
     * 
     * @return
     *     possible object is
     *     {@link Agents }
     *     
     */
    public Agents getAgents() {
        return agents;
    }

    /**
     * Sets the value of the agents property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agents }
     *     
     */
    public void setAgents(Agents value) {
        this.agents = value;
    }

    /**
     * Gets the value of the grantees property.
     * 
     * @return
     *     possible object is
     *     {@link Grantees }
     *     
     */
    public Grantees getGrantees() {
        return grantees;
    }

    /**
     * Sets the value of the grantees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grantees }
     *     
     */
    public void setGrantees(Grantees value) {
        this.grantees = value;
    }

}
