//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 04:03:49 PM EET 
//


package lt.vinco.simple;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication"
})
@XmlRootElement(name = "related-documents")
public class RelatedDocuments {

    @XmlElements({
        @XmlElement(name = "addition", required = true, type = Addition.class),
        @XmlElement(name = "division", required = true, type = Division.class),
        @XmlElement(name = "continuation", required = true, type = Continuation.class),
        @XmlElement(name = "previously-filed-application", required = true, type = PreviouslyFiledApplication.class),
        @XmlElement(name = "continuation-in-part", required = true, type = ContinuationInPart.class),
        @XmlElement(name = "continuing-reissue", required = true, type = ContinuingReissue.class),
        @XmlElement(name = "reissue", required = true, type = Reissue.class),
        @XmlElement(name = "reexamination", required = true, type = Reexamination.class),
        @XmlElement(name = "substitution", required = true, type = Substitution.class),
        @XmlElement(name = "utility-model-basis", required = true, type = UtilityModelBasis.class),
        @XmlElement(name = "correction", required = true, type = Correction.class),
        @XmlElement(name = "related-publication", required = true, type = RelatedPublication.class)
    })
    protected List<Object> additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication;

    /**
     * Gets the value of the additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Addition }
     * {@link Division }
     * {@link Continuation }
     * {@link PreviouslyFiledApplication }
     * {@link ContinuationInPart }
     * {@link ContinuingReissue }
     * {@link Reissue }
     * {@link Reexamination }
     * {@link Substitution }
     * {@link UtilityModelBasis }
     * {@link Correction }
     * {@link RelatedPublication }
     * 
     * 
     */
    public List<Object> getAdditionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication() {
        if (additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication == null) {
            additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication = new ArrayList<Object>();
        }
        return this.additionOrDivisionOrContinuationOrPreviouslyFiledApplicationOrContinuationInPartOrContinuingReissueOrReissueOrReexaminationOrSubstitutionOrUtilityModelBasisOrCorrectionOrRelatedPublication;
    }

}
